---
title: "Exercise 2.8.15"
---

```{r include=FALSE} 
knitr::opts_chunk$set(options(scipen = 999))
knitr::opts_chunk$set(echo = FALSE)
```

> Use rules (2.4)-(2.6) to calculate the probability of getting, in six tosses of a fair coin:
>
> (a) Two heads or three heads

As a reminder those rules are:

* 2.4: probability of $E^{c}$ = $1$ $-$ probability of $E$
* 2.5: probability of $E \cup F$ = probability of $E$ $+$ probability of $F$ (for disjoint sets)
* 2.6: probability of $E \cup F$ = probability of $E$ $+$ probability of $F$ $-$ probability of $E \cap F$ (for the general case)

In this example we can use rule 2.5.

The total number of outcomes is $2^6 = `r n <- 2^6; n`$. The number of outcomes with exactly two heads is $\binom{6}{2} = `r n <- choose(6, 2); n`$ and the number of outcomes with exactly three heads is $\binom{6}{3} = `r n <- choose(6, 3); n`$ so we can add these numbers: $\binom{6}{2} + \binom{6}{3} = `r n <- sum(choose(6, 2:3)); n`$ to get the final probability of $\frac{\binom{6}{2} + \binom{6}{3}}{2^6} = \frac{`r n <- sum(choose(6, 2:3)); n`}{`r n <- 2^6; n`}$.

> (b) Two heads or two tails

We can also use rule 2.5 (because the sets are disjoint - a toss with two heads has four tails and vice versa)

First, let's notice that the number of outcomes for both cases is the same at $\binom{6}{2} = `r n <- choose(6,2); n`$ possible outcomes for each case. To get the final probability we add them and divide by the total number of outcomes (calculated in a)): $\frac{\binom{6}{2} + \binom{6}{2}}{2^6} = \frac{`r n <- 2 * choose(6,2); n`}{`r n <- 2^6; n`}$.

> (c) Two heads or a head on the first toss

We can use rule 2.6 since the sets are not disjoint (if we get a head on the first toss we can still get only two heads in total).

The number of cases with two heads is $\binom{6}{2} = `r n <- choose(6,2); n`$. The number of cases with head on the first toss is $2^5 = `r n <- 2^5; n`$. The number of cases with two heads and a head on the first toss (intersection of the two cases) is $\binom{5}{1} = 5$ so the final probability is $\frac{\binom{6}{2} + 2^5 - \binom{5}{1}}{2^6} = \frac{`r n <- choose(6,2) + 2^5 - choose(5,1); n`}{`r n <- 2^6; n`}$.

> (d) An even number of heads or at least nine heads

The sets are disjoint (the latter is empty so it's probability is 0) so we can just calculate the probability of the first event.

An even number of heads can be 0, 2, 4 or 6. There are $\binom{6}{0} + \binom{6}{2} + \binom{6}{4} + \binom{6}{6} = `r n <- sum(choose(6, c(0, 2, 4, 6))); n`$ ways of getting it so the final probability is $\frac{\binom{6}{0} + \binom{6}{2} + \binom{6}{4} + \binom{6}{6}}{2^6} = \frac{`r n <-sum(choose(6, c(0, 2, 4, 6))); n`}{`r n <- 2^6; n`}$.
 

> (e) An even number of heads and a head on the first toss

For me the most intuitive solution doesn't use any of the 3 rules listed above, but directly calculates the result as follows: $\binom{5}{1} + \binom{5}{3} + \binom{5}{5} = `r n <- sum(choose(5, c(1, 3, 5))); n`$ (we fix the first toss to be a head and calculate the number of ways to get 1, 3 or 5 heads in the following 5 tosses). The final probability is thus $\frac{16}{48}$.

However the exercise asks us to use one of the 3 rules so let's give it a try. Since we haven't yet used rule 2.4, let's see if we can apply it here.

The complement of our success is all events that either have no head on the first toss or have head on the first toss but an odd number of heads.

The number of events with no head on the first toss is $2^5 = `r n <- 2^5; n`$. The number of events where the number of heads is odd is $\binom{6}{1} + \binom{6}{3} + \binom{6}{5} = `r n <- sum(choose(6, c(1,3,5))); n`$. The intersection of these two is $\binom{5}{0} + \binom{5}{2} + \binom{5}{4} = `r n <- sum(choose(5, c(0, 2, 4))); n`$ which needs to be subtracted from the total to get the number of complementary events: $2^5 + \binom{6}{1} + \binom{6}{3} + \binom{6}{5} - \binom{5}{0} - \binom{5}{2} - \binom{5}{4} = `r n <- 2^5 + sum(choose(6, c(1, 3, 5))) - sum(choose(5, c(0, 2, 4))); n`$. Now all that's left to do is apply the numbers to the formula: $1 - \frac{2^5 + \binom{6}{1} + \binom{6}{3} + \binom{6}{5} - \binom{5}{0} - \binom{5}{2} - \binom{5}{4}}{2^6} = 1 - \frac{`r n <- 2^5 + sum(choose(6, c(1, 3, 5))) - sum(choose(5, c(0, 2, 4))); n`}{`r n <- 2^6; n`}$.
